   name = "excel-generator"
   type = "javascript"
   workers_dev = true
   compatibility_date = "2023-10-01"
   main = "src/index.js"

   [build]
   command = "webpack"
   upload.format = "service-worker"
   upload.dir = "./dist"

   [vars]
   TEMPLATE_URL = "TEMPLATE_URL"